service: tsugitasu-authorization

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

functions:
  # 仮登録API
  tmp:
    handler: entry_tmp.handler
    events:
      - http:
          path: /user/entry/tmp/
          method: post
          cors: 
            # どのオリジンからのアクセスを受け付けるかどうか
            origin: '*'
            # 許可するヘッダーを定義
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  # signup時に入力したmailやnicknameをDBにも格納
  postConfirmation:
    handler: postConfirmation.handler
    events:
      - cognitoUserPool:
          # pool: ${self:service}-${self:provider.stage}-user-pool
          pool: ${self:service}-${self:provider.stage}-user-pool
          # trigger: PostConfirmation
          trigger: PreSignUp
          existing: true
  # 本登録API
  prd:
    handler: entry_prd.handler
    events:
      - http:
          path: /user/entry/prd/
          method: post
          cors: 
            # どのオリジンからのアクセスを受け付けるかどうか(今回は全て)
            origin: '*'
            # 許可するヘッダーを定義
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

  # ログインAPI
  login:
    handler: login.handler
    events:
      - http:
          path: /user/login/
          method: post
          cors: 
            # どのオリジンからのアクセスを受け付けるかどうか(今回は全て)
            origin: '*'
            # 許可するヘッダーを定義
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

resources:
  Resources:
    ApiGatewayWithAuthorizationUserPool:
      # ユーザプール作る時にやった諸々の設定
      Type: 'AWS::Cognito::UserPool'
      Properties:
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: 'verified_email'
              Priority: 1
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          InviteMessageTemplate:
            EmailMessage: 'Your username is {username} and temporary password is {####}.'
            EmailSubject: 'Your temporary password'
            SMSMessage: 'Your username is {username} and temporary password is {####}.'
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: false
          DeviceOnlyRememberedOnUserPrompt: true
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        EmailVerificationMessage: '認証コードは<br>{####}<br>です。'
        EmailVerificationSubject: '認証コードのお知らせ'
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 365
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: email
            Required: true
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: nickname
            Required: false
        SmsAuthenticationMessage: 'Your verification code is {####}.'
        SmsVerificationMessage: 'Your verification code is {####}.'
        UsernameConfiguration:
          CaseSensitive: true
        UserPoolAddOns:
          AdvancedSecurityMode: AUDIT
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        UserPoolTags:
          Service: ${self:service}-${self:provider.stage}
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE #
          EmailMessage: '認証コードは<br>{####}<br>です。'
          EmailSubject: '認証コードのお知らせ'
          SmsMessage: 'Your verification code is {####}.'

    ApiGatewayWithAuthorizationUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        CallbackURLs:
          - 'http://localhost:3000'
        ClientName: ${self:service}-${self:provider.stage}-user-pool-client
        DefaultRedirectURI: 'http://localhost:3000'
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        LogoutURLs:
          - 'http://localhost:3000'
        PreventUserExistenceErrors: ENABLED
        ReadAttributes:
          - email
          - nickname
        RefreshTokenValidity: 10
        SupportedIdentityProviders:
          - COGNITO
        UserPoolId:
          Ref: ApiGatewayWithAuthorizationUserPool
        WriteAttributes:
          - email
          - nickname

    ApiGatewayWithAuthorizationAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      DependsOn:
        - ApiGatewayRestApi  # sls frameworkが勝手にこの名前で作成してる
      Properties:
        Name: ApiGatewayWithAuthorizationAuthorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        IdentitySource: method.request.header.Authorization
        Type: COGNITO_USER_POOLS
        # 認可に用いるユーザプールのARNを指定
        ProviderARNs:
          - Fn::GetAtt: [ ApiGatewayWithAuthorizationUserPool, Arn ]

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

  # cloudformationの出力(コンソール等で確認可能)
  Outputs:
    CognitoUserPoolId:
      Value:
        Ref: ApiGatewayWithAuthorizationUserPool
    CognitoUserPoolIdARN:
      Value: { Fn::GetAtt: [ ApiGatewayWithAuthorizationUserPool, Arn ] }
    CognitoUserPoolClientId:
      Value:
        Ref: ApiGatewayWithAuthorizationUserPoolClient
